server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.57:8082/eureka/

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: client-microservice
          uri: http://192.168.1.57:8091
          predicates:
            - Path=/api/clients/**
        - id: bankaccounts-microservice
          uri: http://192.168.1.57:8092
          predicates:
            - Path=/api/accounts/**
        - id: bankdeposit-microservice
          uri: http://192.168.1.57:8093
          predicates:
            - Path=/api/deposit/**
        - id: bankwithdrawal-microservice
          uri: http://192.168.1.57:8094
          predicates:
            - Path=/api/withdrawal/**
        - id: bankcredit-microservice
          uri: http://192.168.1.57:8095
          predicates:
            - Path=/api/credit/**
        - id: bankcreditcard-microservice
          uri: http://192.168.1.57:8096
          predicates:
            - Path=/api/creditcard/**
        - id: yankee-account-service
          uri: http://192.168.1.57:8097
          predicates:
            - Path=/api/creditcard/**
            