server:
  port: 8096

spring:
  data:
    mongodb:
      #uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/creditcard?retryWrites=true&w=majority
      uri: mongodb+srv://developer:developer@cluster0.aa6qr.mongodb.net/accounts?retryWrites=true&w=majority
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  info:
    env:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
      
apiclient:
  uri: http://192.168.1.57:8083
microservice-clients:
  uri: /api/clients/
microservice-accounts:
  uri: /api/accounts/
microservice-creditcard:
  uri: /api/creditcard/
