server:
  port: 8094
spring:
  application:
    name: bankwithdrawal-microservice
  data:
    mongodb:
      #uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/withdrawal?retryWrites=true&w=majority
      uri: mongodb+srv://developer:developer@cluster0.aa6qr.mongodb.net/withdrawal?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.57:8082/eureka

info:
  application:
    name : bankdeposit-microservice
    Description : This is a Microservice to manage deposits
    artifact : bank-clients
    version : '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: 2.6.4


resilience4j:
  circuitbreaker.:
    instances:
      saveWithdrawalCB:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
      getWithdrawalCB:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true

resilience4j.timelimiter:
    instances:
      saveWithdrawalCB:
        timeoutDuration: 2000ms
        cancelRunningFuture: true
      getWithdrawalCB:
        timeoutDuration: 2000ms
        cancelRunningFuture: true