server:
  port: 8098
spring:
  application:
    name: bootcoin-microservice
  data:
    mongodb:
      #uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/deposit?retryWrites=true&w=majority
      uri: mongodb+srv://developer:developer@cluster0.aa6qr.mongodb.net/deposit?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.57:8082/eureka
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  info:
    env:
      enabled: true
info:
  application:
    name : bankdeposit-microservice
    Description : This is a Microservice to manage deposits
    artifact : bank-bootcoin
    version : '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: 2.6.4


